links:
  - /politica-de-cookies
  - /cookies
  - /plugins/asesor-cookies-para-la-ley-en-espana
  - /politica_cookies-es.php
  - /politica-cookies
  - /index.php/politica-de-cookies
  - /politica-de-cookies.html
  - /politica_cookies
  - /politica-cookies.jsp
  - /informacion-sobre-cookies
  - /uso-de-cookies
  - /politicaCookies.jsp
